---
- name: Install Java
  apt:
    name: openjdk-17-jre
    state: present

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start
  wait_for:
    port: 8080
    timeout: 300

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  notify: Restart Jenkins

- name: Display initial admin password
  shell: |
    if [ -f /var/lib/jenkins/secrets/initialAdminPassword ]; then
      cat /var/lib/jenkins/secrets/initialAdminPassword
    else
      echo "Password file not found yet. Please wait and check Jenkins logs."
      journalctl -u jenkins --no-pager | grep "InitialAdminPassword"
    fi
  register: jenkins_password
  changed_when: false

- name: Show password message
  debug:
    msg: "Initial admin password: {{ jenkins_password.stdout }}"
