---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - gnupg
      - software-properties-common
      - ca-certificates
      - git
    state: present
