---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker-ce

- name: Install Docker components
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure project directory exists
  file:
    path: /opt/ci-project
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy project files
  copy:
    src: "files/"  # Копируем ВСЁ (включая Dockerfile и html/)
    dest: "/opt/ci-project/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Build Docker image
  community.docker.docker_image:
    name: nginx-ci
    build:
      path: /opt/ci-project  # Путь к Dockerfile
    source: build
    state: present

- name: Run container
  community.docker.docker_container:
    name: nginx-ci
    image: nginx-ci
    ports:
      - "9889:80"
    state: started
    restart_policy: unless-stopped

